### ISSUE TITLE
Trademarked Logo needs to be removed

### ISSUE THREAD

**Issue by mdrejhon** [Slamy/motionTestSuite#1]
The trademarked UFO logo is copyright Blur Busters (Rejhon Technologies Inc), which I own and operate...

https://github.com/Slamy/motionTestSuite/blob/master/ufo.bmp

Please remove the UFO (including delete from commit history) and use a different graphic. 

Thank you!

**Comment by Slamy** [comment]
I should have known better and asked before usage. It is now removed from the commit history and replaced with a custom graphic.
But I've also added a manual to the readme for users who really want the official test ufo image. I hope that this solution is ok for you as at least the copyrighted material is no longer part of this project. Please reopen this issue if this is still a problem for you.

**Comment by mdrejhon** [comment]
Thank you!
